name: colorado-buffaloes
favicon: null
layout_spectrum: 0.8251399546861649
typography_spectrum: 0.18150717834942043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7314394167624414
  lightness: 0.7338096359744668
  saturation: 0.5280634760856628
  rhythmicContrast: 0.1401393380947411
purpose: []
